---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "fullname" $ -}}-services-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    tier: app
    purpose: deploy
    deployment: helm
    lifecycle: {{ required "REQUIRED: lifecycle" .Values.lifecycle }} 
spec:
  generators:
  - matrix:
      generators:
        - git:
            repoURL: git@github.com:{{- required "github_org" .Values.github_org -}}/{{- required "repo_name" .Values.repo_name -}}.git
            revision: {{ .Values.revision }}
            files:
            - path: {{ include "services_filepath" $ }}
        - clusters: {}
  template:
    metadata:
      {{- if .Values.multi_cluster }}
      name: '{{ "{{ nameNormalized }}" }}-{{ "{{ app.lifecycle }}" }}-{{- .Values.app_name -}}-{{ "{{ path.basename }}" }}-deploy'
      {{- else }}
      name: '{{ "{{ app.lifecycle }}" }}-{{- .Values.app_name -}}-{{ "{{ path.basename }}" }}-deploy'
      {{- end }}
      labels:
        {{- if .Values.multi_cluster }}
        cluster: '{{ "{{ nameNormalized }}" }}'
        {{- end }}
        deployment: helm
        tier: app
        purpose: deploy
        app: {{ .Values.app_name }}
        service: '{{ "{{ path.basename }}" }}'
        lifecycle: {{ required "REQUIRED: lifecycle" .Values.lifecycle }} 
      annotations:
        argocd-image-updater.argoproj.io/image-list: 'appimage=gcr.io/{{- required "app_project_id" .Values.app_project_id -}}/{{- .Values.app_name -}}/{{ "{{ app.lifecycle }}" }}/{{ "{{ path.basename }}" }}'
        argocd-image-updater.argoproj.io/write-back-method: git

        argocd-image-updater.argoproj.io/appimage.pull-secret: pullsecret:argocd/gcr-credentials 
        argocd-image-updater.argoproj.io/appimage.force-update: "true"
        argocd-image-updater.argoproj.io/appimage.update-strategy: latest

        argocd.argoproj.io/sync-wave: '{{ "{{ app.syncWave }}" }}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: {{ .Values.argocd_project }}
      source:
        repoURL: git@github.com:{{- .Values.github_org -}}/{{- .Values.repo_name -}}.git
        targetRevision: {{ .Values.target_revision }}
        path: '{{ "{{ path }}" }}/chart'
        helm:
          {{- if .Values.multi_cluster }}
          releaseName: '{{ "{{ nameNormalized }}" }}-{{ "{{ app.lifecycle }}" }}-{{- .Values.app_name -}}-{{ "{{ path.basename }}" }}'
          {{- else }}
          releaseName: '{{ "{{ app.lifecycle }}" }}-{{- .Values.app_name -}}-{{ "{{ path.basename }}" }}'
          {{- end }}
          ignoreMissingValueFiles: true
          values: |
            web-app:
              {{- if .Values.multi_cluster }}
              cpl_cluster_name: {{ .Values.cpl_cluster_name }}
              cluster_name: {{ "{{ server }}" }}
              {{- end }}
              github_org: {{ .Values.github_org }}
              project_id: {{ .Values.app_project_id }}
              sa_project_id: {{ .Values.sa_project_id }}
              app_code: {{ .Values.app_name }}
              domain: '{{ required "app_domain" .Values.app_domain }}'
              create_infra: false
              microservice_name: '{{ "{{ path.basename }}" }}'
              lifecycle: {{ required "REQUIRED: lifecycle" .Values.lifecycle }} 
      destination:
        server: '{{ "{{ server }}" }}'
        namespace: '{{ include "deploy_namespace" $ }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true


