---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "fullname" $ -}}-services-infra
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    tier: app
    purpose: infra
    deployment: helm
spec:
  generators:
  - git:
      repoURL: git@github.com:{{- .Values.github_org -}}/{{- .Values.repo_name -}}.git
      revision: {{ .Values.revision }}
      files:
      - path: {{ include "services_filepath" $ }}
  template:
    metadata:
      name: '{{ "{{ app.lifecycle }}" }}-{{- .Values.app_name -}}-{{ "{{ path.basename }}" }}-infra'
      labels:
        deployment: helm
        tier: app
        purpose: infra
        app: {{ .Values.app_name }}
        service: '{{ "{{ path.basename }}" }}'
        lifecycle: '{{ "{{ app.lifecycle }}" }}'
      annotations:
        argocd.argoproj.io/sync-wave: '-20'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: {{ .Values.argocd_project }}
      source:
        repoURL: git@github.com:{{- .Values.github_org -}}/{{- .Values.repo_name -}}.git
        path: '{{ "{{ path }}" }}/web-app'
        targetRevision: {{ .Values.target_revision }}
        helm:
          releaseName: '{{ "{{ app.lifecycle }}" }}-{{- .Values.app_name -}}-{{ "{{ path.basename }}" }}'
          ignoreMissingValueFiles: true
          values: |
            web-app:
              github_org: {{ .Values.github_org }}
              project_id: {{ .Values.app_project_id }}
              sa_project_id: {{ .Values.sa_project_id }}
              app_code: {{ .Values.app_name }}
              domain: '{{ "{{ app.domain }}" }}'
              deploy_app: false
              microservice_name: '{{ "{{ path.basename }}" }}'
              lifecycle: '{{ "{{ app.lifecycle }}" }}'
          valueFiles:
          - './services/{{ "{{ path.basename }}" }}.yaml'
          - './services/{{ "{{ path.basename }}" }}/{{ "{{ app.lifecycle }}" }}.yaml'
      destination:
        server: {{ .Values.infra.server }}
        namespace: '{{ "{{ app.lifecycle }}" }}-{{- .Values.app_name -}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

