apiVersion: v2
name: external-secrets
description: External Secrets Operator
type: application
version: 0.0.9

dependencies:
- name: external-secrets
  version: 0.5.6
  repository: https://charts.external-secrets.io 
- name: app-iam
  version: 0.0.5
  repository: "https://pixovr.github.io/helm-charts"
  alias: app_iam
