
github_org: PixoVR
repo_name: replaceme
revision: HEAD

app_project_id: replaceme
sa_project_id: replaceme

app_name: sample

multi_cluster: true
cpl_cluster_name: "us-central1"

pre_tenant_services_filepath: kustomize/tenants
post_tenant_services_filepath: services/*
post_tenant_services_filename: app-config.yaml

services_filepath: ''

destination_server: https://kubernetes.default.svc
target_revision: HEAD

argocd_namespace: argocd
argocd_project: platform

app:
  server: https://kubernetes.default.svc
  namespace: ''

infra:
  server: https://kubernetes.default.svc
  namespace: ''
