
github_org: PixoVR
repo_name: replaceme
revision: HEAD

app_name: sample

pre_tenant_services_filepath: kustomize/tenants
post_tenant_services_filepath: services/*/*app-config.yaml

services_filepath: ''

destination_server: https://kubernetes.default.svc
target_revision: HEAD

argocd_namespace: argocd
argocd_project: platform

iam:
  server: https://kubernetes.default.svc

app:
  server: https://kubernetes.default.svc

infra:
  server: https://kubernetes.default.svc
