apiVersion: v2
name: opa-gatekeeper
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
- name: gatekeeper
  version: 3.7.1
  repository: https://open-policy-agent.github.io/gatekeeper/charts
