---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: in-cluster
  namespace: {{ .Release.Namespace }}
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: in-cluster
  namespace: {{ .Release.Namespace }}
spec:
  credentials:
    source: InjectedIdentity