{{- with .Values.gcp.serviceAccount }}
{{- if .enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
{{- with .labels }}
  labels:
{{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- with .annotations }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "sa_email" $ }}
{{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- with .Values.kubernetes.serviceAccount }}
{{- if .enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
{{- with .labels }}
  labels:
{{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- with .annotations }}
  annotations:
{{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
