
add_bindings: false

app:
  namespace: ''
  ksa_name: workload-sa
  roles:
    - cloudsql.client
    - cloudsql.instanceUser
    - errorreporting.writer
    - iam.serviceAccountTokenCreator
    - logging.logWriter
    - monitoring.metricWriter
    - storage.admin

infra:
  namespace: ''

