
enabled: true
add_bindings: false

target_namespace: infra-admin

config_connector:
  enabled: false

app:
  namespace: ''
  ksa_name: workload-sa
  roles:
    - cloudsql.client
    - cloudsql.instanceUser
    - errorreporting.writer
    - iam.serviceAccountTokenCreator
    - logging.logWriter
    - monitoring.metricWriter
    - storage.admin

infra:
  namespace: ''
  ksa_name: infra-admin
