

app:
  namespace: ''
  ksa_name: ''
  roles:
    - cloudsql.client
    - cloudsql.instanceUser
    - errorreporting.writer
    - iam.serviceAccountTokenCreator
    - logging.logWriter
    - monitoring.metricWriter
    - storage.admin

infra:
  namespace: ''

