
enabled: true
local: false
non_preemptible: false
create_infra: true
deploy_app: true

nginx: false
node: false

debug:
  enabled: false
  containerPort: 40000

add_lifecycle_to_domain: false
extra_domain: ''
extra_subdomain: ''

github_org: PixoVR
lifecycle: dev
app_code: sample
microservice_name: web
default_branch: main

repo_name: replaceme
build_context: '.'
build_cache: 'true'
dockerfile: Dockerfile

app_iam:
  add_bindings: true

ksa_name: app-workload

infra:
  sa_name: app-infra

external_auth: false

linkerd:
  enabled: true

crunchydb:
  enabled: false
  create: true
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-2
  pgbackrest:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
  pg_version: 14
  disk_size: 20Gi

toleration: ''

primary_cluster_name: central-cluster
primary_cluster: central-cluster-membership

create_sa: true

demo:
  enabled: false
  image: nginx

image:
  name: ""
  tag: latest

containerPort: 80

healthCheck:
  enabled: true
  path: /

submodules:
  enabled: false
  secret_name: api-submodule-reader-private-key

sql:
  proxy: false

cache:
  enabled: false

memory:
  request: 128Mi
  limit: 256Mi
cpu:
  request: .1
  limit: .25

replicas: 1

max_replicas: 20
target_cpu: 80
target_mem: 256Mi

workflows:
  artifacts:
    enabled: false

email:
  enabled: false
  mfa: false
  sender: ''
  bcc: ''

aws:
  auth:
    enabled: false
  cloudfront:
    enabled: false

google:
  region: us-central1
  zone: us-central1-a
  cdn:
    enabled: false
  config_connector_context: false
  create_ip: false
  create_cloudbuild: true
  cloudbuild:
    default: true
    filename: cloudbuild.yaml
    gke: false
  create_registry: false
  create_monitoring_suite: false
  notification_channel: ""
  registry: gcr.io
  pubsub:
    enabled: false
    add_label: false
    schemas: []
    topics: []
    subscription:
      ackDeadlineSeconds: 15
      enableMessageOrdering: true
      messageRetentionDuration: 86400s
      retainAckedMessages: false
      subscriptions: []
  sql:
    enabled: false
    use_iam: true
    extra_databases: []
  storage:
    enabled: false
    create: false
    notifications: false
    cors:
      allow_all: false
      maxAgeSeconds: 3600
      headers:
        - "Accept"
        - "Access-Control-Request-Headers"
        - "Access-Control-Request-Method"
        - "Access-Control-Allow-Origin"
        - "Accept-Encoding"
        - "Accept-Language"
        - "Cache-Control"
        - "Connection"
        - "Content-Length"
        - "Content-Range"
        - "Content-Type"
        - "Host"
        - "Origin"
        - "Pragma"
        - "Referer"
        - "Sec-Ch-Ua"
        - "Sec-Ch-Ua-Mobile"
        - "Sec-Ch-Ua-Platform"
        - "Sec-Fetch-Dest"
        - "Sec-Fetch-Mode"
        - "Sec-Fetch-Site"
        - "User-Agent"
        - "X-Client-Data"
        - "Date"
        - "Server"
        - "Vary"
        - "X-Access-Token"
        - 'X-Goog-Resumable'
    retentionPolicy:
      isLocked: false
      retentionPeriod: 1
    bucket_list:
      - name: modules
        key: MODULES
  iap:
    enabled: false
    test:
      enabled: false
  analytics:
    enabled: false
  wi_test: false

security_policy: no-russia
ssl_policy: tls-12

github:
  credentials:
    enabled: false
    ssh:
      enabled: true
    pat:
      enabled: true
    https:
      enabled: false

oauth:
  google:
    enabled: false

  github:
    enabled: false

  facebook:
    enabled: false

  twitter:
    enabled: false

external_dns:
  enabled: true

external_secrets:
  enabled: false
  secret_store:
    enabled: false
    name: pixo-secret-store
  cluster_secret_store:
    enabled: false
    name: pixo-secret-store
  app_secrets:
    enabled: false
    create: false
  refresh_interval: 0

secrets:
  enabled: false

cert_manager:
  enabled: false

deployment:
  enabled: true
  pvc:
    enabled: false
    path: /var/sqlite
    disk_size: 5Gi

service:
  internal: true
  type: ClusterIP

ingress:
  enabled: true
  override: false
  bring_ip: false
  https: true
  cert: false
  mci: false
  nginx: false
  rewrite_target: /
  websocket: false

network_policy:
  enabled: false

acm:
  enabled: false

autoscaler:
  enabled: false

db:
  proxy: false
  host: "127.0.0.1"
  port: "5432"
  password: fakepassword
  proxy_version: gcr.io/cloudsql-docker/gce-proxy:1.32.0
  host_env_key: DB_HOST
  port_env_key: DB_PORT
  name_env_key: DB_NAME
  user_env_key: DB_USER

sendgrid:
  enabled: false

cilium:
  enabled: false

cronjob:
  enabled: false
  image:
    name: alpine/httpie
    tag: latest
  schedule: '0 8 * * *'
  external_secrets:
    enabled: false
    secrets: []

sa_name: workload

kaniko_version_tag: v1.16.0
ci_machine_type: E2_HIGHCPU_8

clamav:
  enabled: false
  pvc:
    enabled: true
    disk_size: 3Gi

sa_json_key:
  enabled: false
  envKey: GOOGLE_APPLICATION_CREDENTIALS

