apiVersion: v2
name: crossplane
description: A Helm chart for Kubernetes
type: application
version: 0.0.10

dependencies:
- name: crossplane
  version: 1.8.1
  repository: https://charts.crossplane.io/stable
- name: app-iam
  version: 0.0.6
  repository: "https://pixovr.github.io/helm-charts"
  alias: app_iam
