
github_org: PixoVR
repo_name: replaceme
revision: HEAD

argocd_project_name: platform
file_path: kustomize/tenants/*/config.yaml
destination_server: https://kubernetes.default.svc
argocd_namespace: argocd
target_revision: HEAD

apps:
  enabled: true
  chart:
    repoURL: https://pixovr.github.io/helm-charts
    name: argocd-app-deploy
    version: 0.0.17

infra_namespace: infra-admin
iam_namespace: infra-admin
