
apiVersion: v1
kind: Secret
metadata:
  name: gcp-account-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  credentials: {{ required "REQUIRED: gcp_account_creds" .Values.gcp_account_creds | b64enc }}

---

apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: {{ required "REQUIRED: gcp_project_id" .Values.gcp_project_id }}
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace }}
      name: gcp-account-creds
      key: credentials
