{{- if .Values.make_subnet }}

apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  name: {{ .Release.Name -}}-subnet
spec:
  providerConfigRef:
    name: default

  forProvider:
    networkRef:
      name: {{ .Release.Name }}-vpc

    region: us-central1
    ipCidrRange: 192.168.0.0/24
    privateIpGoogleAccess: true
    secondaryIpRanges:
      - rangeName: pods
        ipCidrRange: 10.0.0.0/8
      - rangeName: services
        ipCidrRange: 172.16.0.0/16

  writeConnectionSecretToRef:
    name: {{ .Release.Name -}}-subnet-ref

{{- end }}
