{{- if .Values.create_infra }}
{{- if not .Values.demo.enabled }}
{{- if .Values.google.create_cloudbuild }}

apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: {{ include "deployment_name" $ -}}-ci
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" . }}
  labels:
    namespace: {{ .Release.Namespace }}
spec:
  disabled: {{ not .Values.enabled }}
  github:
    owner: {{ required "REQUIRED: github_org" .Values.github_org }}
    name: {{ required "REQUIRED: repo_name" .Values.repo_name }} 
    push:
      branch: "^{{- include "branch" . -}}$"

  {{- if ne .Values.build_context "." }}
  includedFiles:
    - "{{ .Values.build_context -}}/**"
  {{- end }}

  build:
    timeout: 1800s
    options:
      machineType: E2_HIGHCPU_8

    step:
      {{- if .Values.submodules.enabled }}
      - id: Store-SSH-Key
        name: 'gcr.io/cloud-builders/git'
        secretEnv: ['SSH_KEY']
        entrypoint: 'bash'
        args:
        - -c
        - |
          echo "$$SSH_KEY" >> /root/.ssh/id_rsa
          chmod 400 /root/.ssh/id_rsa
          cp known_hosts.github /root/.ssh/known_hosts
        volumes:
        - name: 'ssh'
          path: /root/.ssh

      - id: "Pull-Submodules"
        name: gcr.io/cloud-builders/git
        args: ['submodule', 'update', '--init', '--recursive']
        volumes:
        - name: 'ssh'
          path: /root/.ssh
      {{- end }}

      - id: "Build-Image"
        name: "gcr.io/kaniko-project/executor:v1.6.0"
        args:
          - --destination={{- include "registry" . }}:$COMMIT_SHA
          - --destination={{- include "registry" . }}:latest
          - --context={{- required "REQUIRED: build_context" .Values.build_context }}
          - --dockerfile={{- include "dockerfile" $ }}
          - --cache={{- .Values.build_cache }}
          - --cache-ttl=240h

{{- if .Values.submodules.enabled }}
    availableSecrets:
      secretManager:
      - env: 'SSH_KEY'
        versionRef:
          name: {{ include "submodule_secret_version_name" $ }}

---

apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: {{ include "submodule_secret_name" $ }}
spec:
  replication:
    userManaged:
      replicas:
      - location: us-central1
      - location: us-east4
---

apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: {{ include "submodule_secret_version_name" $ }}
spec:
  enabled: true
  secretData:
    value: c2VjcmV0MQ==
  secretRef:
    name: {{ include "submodule_secret_name" $ }}

{{- end }}

{{- end }}
{{- end }}
{{- end }}
