{{- if .Values.create_infra }}
{{- if not .Values.demo.enabled }}
{{- if .Values.google.create_cloudbuild }}

apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: {{ include "deployment_name" $ -}}-ci
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project" . }}
  labels:
    namespace: {{ .Release.Namespace }}
spec:
  disabled: {{ not .Values.enabled }}
  github:
    owner: {{ required "REQUIRED: github_org" .Values.github_org }}
    name: {{ required "REQUIRED: repo_name" .Values.repo_name }} 
    push:
      branch: "^{{- include "branch" . -}}$"
  build:
    timeout: 1800s
    options:
      machineType: E2_HIGHCPU_8

    step:
      - id: "Build-Image"
        name: "gcr.io/cloud-builders/docker"
        args:
          - build
          - -t
          - {{- include "registry" . }}:$COMMIT_SHA
          - -t
          - {{- include "registry" . }}:latest
          - --cache-from
          - {{- include "registry" . }}:latest
          - .
      - id: "Push-Image-Commit"
        name: "gcr.io/cloud-builders/docker"
        args:
          - push
          - {{- include "registry" . }}:$COMMIT_SHA
      - id: "Push-Image-Latest"
        name: "gcr.io/cloud-builders/docker"
        args:
          - push
          - {{- include "registry" . }}:latest

{{- end }}
{{- end }}
{{- end }}
