{{- if .Values.create_infra }}
{{- if .Values.google.sql.enabled }}

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ include "lifecycle" $ -}}-db
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "db_project_id" $ }}
  labels:
    namespace: {{ $.Release.Namespace }}
    backstage.io/kubernetes-id: {{ $.Values.app_code }}
spec:
  instanceRef:
    external: {{ include "instance_name" $ }}

---

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ include "app_label" $ }}-user
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "db_project_id" $ }}
  labels:
    namespace: {{ $.Release.Namespace }}
    backstage.io/kubernetes-id: {{ $.Values.app_code }}
spec:
  instanceRef:
    external: {{ include "instance_name" $ }}
  resourceID: {{ include "app_sa" $ }}
  type: CLOUD_IAM_SERVICE_ACCOUNT

{{- end }}
{{- end }}
