{{- if .Values.create_infra }}
{{- if not .Values.demo.enabled }}
{{- if .Values.google.create_cloudbuild }}

apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: {{ include "deployment_name" $ -}}-ci
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" . }}
  labels:
    namespace: {{ .Release.Namespace }}
spec:
  disabled: {{ not .Values.enabled }}
  github:
    owner: {{ required "REQUIRED: github_org" .Values.github_org }}
    name: {{ required "REQUIRED: repo_name" .Values.repo_name }} 
    push:
      branch: "^{{- include "branch" . -}}$"

  {{- if ne .Values.build_context "." }}
  includedFiles:
    - "{{ .Values.build_context -}}/**"
  {{- end }}

  build:
    timeout: 1800s
    options:
      machineType: E2_HIGHCPU_8

    step:
      {{- if .Values.submodules.enabled }}
      - id: "Pull-Submodules"
        name: gcr.io/cloud-builders/git
        args: ['submodule', 'update', '--init', '--recursive']
      {{- end }}

      - id: "Build-Image"
        name: "gcr.io/kaniko-project/executor:v1.6.0"
        args:
          - --destination={{- include "registry" . }}:$COMMIT_SHA
          - --destination={{- include "registry" . }}:latest
          - --context={{- required "REQUIRED: build_context" .Values.build_context }}
          - --dockerfile={{- include "dockerfile" $ }}
          - --cache={{- .Values.build_cache }}
          - --cache-ttl=240h

{{- end }}
{{- end }}
{{- end }}
