{{- if .Values.cronjob.enabled }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: '{{ include "cronjob_name" $ }}'
spec:
  schedule: "{{- .Values.cronjob.schedule -}}"
  jobTemplate:
    spec:
      template:
        spec:
          hostIPC: false
          hostNetwork: false
          hostPID: false
          securityContext:
            runAsUser: 115
            runAsGroup: 125
            fsGroup: 190
            supplementalGroups:
              - 150
          restartPolicy: Never
          containers:
          - name: http
            image: alpine/httpie
            imagePullPolicy: IfNotPresent

            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              procMount: Default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault

            args:
            - {{ include "service_name" $ -}}.{{- .Release.Namespace -}}.svc:443/{{- .Values.cronjob.endpoint }}
            - key=$(CRON_KEY)
            - --ignore-stdin

            env:
            - name: CRON_KEY
              valueFrom:
                secretKeyRef:
                  name: cron-secret
                  key: CRON_KEY

{{- end }}
