{{- if .Values.enabled }}

{{- range .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: '{{ include "cronjob_name" $ }}-{{- .name -}}-cj'
  labels:
    lifecycle: '{{- include "lifecycle" $ -}}'
    namespace: {{ $.Release.Namespace }}
    app: {{ $.Values.app_code }}
    name: {{ $.Values.microservice_name }}
    tier: application
    {{- if $.Values.datadog.enabled }}
    tags.datadoghq.com/env: '{{- include "lifecycle" $ -}}'
    tags.datadoghq.com/service: '{{- include "app_microservice_name" $ -}}-{{- .name -}}-cj'
    tags.datadoghq.com/version: '{{- $.Values.image.tag -}}'
    {{- end }}
spec:
  {{- if .schedule }}
  schedule: '{{- .schedule -}}'
  {{- else }}
  schedule: '{{- $.Values.cronjob.schedule -}}'
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            lifecycle: '{{- include "lifecycle" $ -}}'
            namespace: {{ $.Release.Namespace }}
            app: {{ $.Values.app_code }}
            name: {{ $.Values.microservice_name }}
            tier: application
            {{- if $.Values.datadog.enabled }}
            tags.datadoghq.com/env: '{{- include "lifecycle" $ -}}'
            tags.datadoghq.com/service: '{{- include "app_microservice_name" $ -}}-{{- .name -}}-cj'
            tags.datadoghq.com/version: '{{- $.Values.image.tag -}}'
            {{- end }}
        spec:
          serviceAccountName: '{{ include "ksa_name" $ }}'
          restartPolicy: Never

          hostIPC: false
          hostNetwork: false
          hostPID: false

          securityContext:
            runAsUser: 115
            runAsGroup: 125
            fsGroup: 190
            supplementalGroups:
              - 150

          volumes:
          - name: tmp-dir
            emptyDir: {}

          containers:
          - name: job

            {{- if .image.self }}
            image: '{{ include "image" $ }}'

            {{- if .image.command }}
            command:
            {{- toYaml .image.command | nindent 12 }}
            {{- end }}

            {{- if .image.args }}
            args:
            {{- toYaml .image.args | nindent 12 }}
            {{- end }}

            {{- else }}

            image: '{{- .image.name -}}:{{- .image.tag -}}'

            {{- if $.Values.deployment.enabled }}
            args:
            - {{ include "service_name" $ -}}.{{- $.Release.Namespace -}}.svc:443/{{- $.Values.cronjob.endpoint }}
            - x-access-token:$(SECRET_KEY)
            - --ignore-stdin
            {{- end }}

            {{- end }}

            imagePullPolicy: IfNotPresent

            resources:
              requests:
                memory: {{ required "REQUIRED: .memory.request" .memory.request }}
                cpu: {{ required "REQUIRED: .cpu.request" .cpu.request }}
              limits:
                memory: {{ required "REQUIRED: .memory.limit" .memory.limit }}
                cpu: {{ required "REQUIRED: .cpu.limit" .cpu.limit }}

            volumeMounts:
            - mountPath: /tmp
              name: tmp-dir

            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              procMount: Default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault

            env:
            {{- if .env }}
            {{- toYaml .env | nindent 12 }}
            {{- end }}

            - name: LIFECYCLE
              value: {{ upper $.Values.lifecycle }}

            {{- if and $.Values.redis.enabled $.Values.redis.auth.enabled }}
            - name: REDIS_USERNAME
              value: {{ $.Values.redis.auth.username }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{- $.Release.Name -}}-{{- $.Values.redis.secret_suffix -}}'
                  key: redis-password
            {{- end }}

            {{- if $.Values.datadog.enabled }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']

            {{- if $.Values.node }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_LOGS_INJECTION
              value: "true"
            {{- end }}
            {{- end }}

            {{- if $.Values.crunchydb.enabled }}
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
                  key: port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
                  key: dbname
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
                  key: password
            {{- else if $.Values.sql.proxy }}
            - name: DB_VENDOR
              value: "postgres"

            - name: {{ upper $.Values.db.host_env_key }}
              value: "{{- $.Values.db.host -}}"

            - name: {{ upper $.Values.db.port_env_key }}
              value: "{{- $.Values.db.port -}}"

            - name: {{ upper $.Values.db.name_env_key }}
              value: '{{- include "db_name" $ -}}'

            - name: {{ upper $.Values.db.user_env_key }}
              value: '{{- include "app_sa" $ -}}'

            {{- end }}

            {{- if $.Values.aws.auth.enabled }}

            {{- if $.Values.aws.auth.region }}
            - name: AWS_REGION
              value: {{ $.Values.aws.auth.region }}
            {{- end }}

            {{- if $.Values.aws.auth.endpoint }}
            - name: AWS_ENDPOINT
              value: {{ $.Values.aws.auth.endpoint }}
            {{- end }}

            {{- if $.Values.aws.bucket }}
            - name: S3_BUCKET_NAME
              value: {{ $.Values.aws.bucket }}
            {{- end }}

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: aws-id

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: aws-secret
            {{- end }}

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: auth-key

            - name: TMP_PATH
              value: "/tmp"

            {{- if $.Values.google.storage.enabled }}

            - name: GCP_PROJECT_ID
              value: '{{- include "app_project_id" $ -}}'

            {{- range $.Values.google.storage.bucket_list }}
            - name: GOOGLE_STORAGE_{{ .key }}
              {{- if ne $.Values.cpl_cluster_name $.Values.cluster_name }}
              value: {{ $.Values.cluster_name -}}-{{- include "microservice_label" $ -}}-{{- .name }}
              {{- else }}
              value: {{ include "microservice_label" $ -}}-{{- .name }}
              {{- end }}
            {{- end }}

            {{- range $.Values.google.storage.external_bucket_list }}
            - name: GOOGLE_STORAGE_{{ .key }}
              {{- if .prefix }}
              value: {{ .prefix -}}-{{ include "lifecycle" $ -}}-{{- .external_service -}}-{{- .name }}
              {{- else }}
              value: {{ include "lifecycle" $ -}}-{{- .external_service -}}-{{- .name }}
              {{- end }}
            {{- end }}

            {{- end }}

            {{- if $.Values.email.enabled }}
            - name: EMAILER_EMAIL
              value: {{ $.Values.email.sender }}
            {{- if $.Values.email.mfa }}
            - name: EMAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email-sender-password
            {{- end }}
            {{- end }}

          {{- if and ($.Values.sql.proxy) (not $.Values.crunchydb.enabled) }}
          - name: proxy
            image: "{{ $.Values.db.proxy_version }}"
            imagePullPolicy: Always
            command:
            - /cloud_sql_proxy
            - -instances={{- include "db_project_id" $ -}}:{{- required "REQUIRED: google.region" $.Values.google.region -}}:{{- include "instance_name" $ }}=tcp:127.0.0.1:5432
            - -enable_iam_login

            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              procMount: Default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
          {{- end }}



{{- end }}

{{- end }}

