{{- if .Values.enabled }}
{{- if .Values.cronjob.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: '{{ include "cronjob_name" $ }}-cronjob'
  labels:
    lifecycle: '{{- include "lifecycle" $ -}}'
    namespace: {{ .Release.Namespace }}
    app: {{ .Values.app_code }}
    name: {{ .Values.microservice_name }}
    tier: application
    {{- if .Values.datadog.enabled }}
    tags.datadoghq.com/env: '{{- include "lifecycle" $ -}}'
    tags.datadoghq.com/service: '{{- include "app_microservice_name" $ -}}-cj'
    tags.datadoghq.com/version: '{{- $.Values.cronjob.image.tag -}}'
    {{- end }}
spec:
  schedule: "{{- .Values.cronjob.schedule -}}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            lifecycle: '{{- include "lifecycle" $ -}}'
            namespace: {{ $.Release.Namespace }}
            app: {{ $.Values.app_code }}
            name: {{ $.Values.microservice_name }}
            tier: application
            {{- if .Values.datadog.enabled }}
            tags.datadoghq.com/env: '{{- include "lifecycle" $ -}}'
            tags.datadoghq.com/service: '{{- include "app_microservice_name" $ -}}-cj'
            tags.datadoghq.com/version: '{{- $.Values.cronjob.image.tag -}}'
            {{- end }}
        spec:
          serviceAccountName: '{{ include "ksa_name" $ }}'
          restartPolicy: Never

          hostIPC: false
          hostNetwork: false
          hostPID: false

          securityContext:
            runAsUser: 115
            runAsGroup: 125
            fsGroup: 190
            supplementalGroups:
              - 150

          volumes:
          - name: tmp-dir
            emptyDir: {}

          containers:
          - name: job
            image: '{{ include "cron_image" $ }}'
            imagePullPolicy: IfNotPresent

            resources:
              requests:
                memory: {{ required "REQUIRED: memory.request" .Values.memory.request }}
                cpu: {{ required "REQUIRED: cpu.request" .Values.cpu.request }}
              limits:
                memory: {{ required "REQUIRED: memory.limit" .Values.memory.limit }}
                cpu: {{ required "REQUIRED: cpu.limit" .Values.cpu.limit }}

            volumeMounts:
            - mountPath: /tmp
              name: tmp-dir

            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              procMount: Default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault

            {{- if .Values.deployment.enabled }}
            args:
            - {{ include "service_name" $ -}}.{{- .Release.Namespace -}}.svc:443/{{- .Values.cronjob.endpoint }}
            - x-access-token:$(SECRET_KEY)
            - --ignore-stdin
            {{- end }}

            env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
            {{- range .Values.dynamicHosts }}

            - name: {{ .key }}
            {{- if eq .type "local" }}
            {{- if .path }}
              value: http://{{ $.Release.Namespace -}}-{{- .service -}}.{{- $.Release.Namespace -}}.svc/{{- .path }}
            {{- else }}
              value: http://{{ $.Release.Namespace -}}-{{- .service -}}.{{- $.Release.Namespace -}}.svc
            {{- end }}

            {{- else if eq .type "remote" }}

              {{ $url := include "lifecycle_domain" $ }}

              {{- if .cluster }}

              {{- if .service }}
              value: {{ .protocol }}://{{- .cluster -}}.{{- .tenant -}}.{{- include "lifecycle_domain" $ -}}/{{- .service }}

              {{- else if .subdomain }}
              value: {{ .protocol }}://{{- .cluster -}}.{{- .subdomain -}}.{{- .tenant -}}.{{- include "lifecycle_domain" $ }}

              {{- else }}
              value: {{ .protocol }}://{{- .cluster -}}.{{- .tenant -}}.{{- include "lifecycle_domain" $ }}
              {{- end }}

              {{- else }}

              {{- if .service }}
              value: {{ .protocol }}://{{- .tenant -}}.{{- include "lifecycle_domain" $ }}/{{- .service }}

              {{- else if .subdomain }}
              value: {{ .protocol }}://{{- .subdomain -}}.{{- .tenant -}}.{{- include "lifecycle_domain" $ }}

              {{- else }}
              value: {{ .protocol }}://{{- .tenant -}}.{{- include "lifecycle_domain" $ }}
              {{- end }}

              {{- end }}

            {{- end }}

            {{- end }}

            - name: LIFECYCLE
              value: {{ upper .Values.lifecycle }}

            {{- if .Values.datadog.enabled }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']

            {{- if .Values.node }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_LOGS_INJECTION
              value: "true"
            {{- end }}
            {{- end }}

            {{- if .Values.aws.auth.enabled }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: aws-id

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: aws-secret
            {{- end }}

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: auth-key

            - name: TMP_PATH
              value: "/tmp"

            {{- if .Values.google.storage.enabled }}

            {{- range .Values.google.storage.bucket_list }}
            - name: GOOGLE_STORAGE_{{ .key }}
              value: {{ include "microservice_label" $ -}}-{{- .name }}
            {{- end }}

            {{- range .Values.google.storage.external_bucket_list }}
            - name: GOOGLE_STORAGE_{{ .key }}
              {{- if .prefix }}
              value: {{ .prefix -}}-{{ include "lifecycle" $ -}}-{{- .external_service -}}-{{- .name }}
              {{- else }}
              value: {{ include "lifecycle" $ -}}-{{- .external_service -}}-{{- .name }}
              {{- end }}
            {{- end }}

            {{- end }}

            {{- if .Values.email.enabled }}
            - name: EMAILER_EMAIL
              value: {{ .Values.email.sender }}
            {{- if .Values.email.mfa }}
            - name: EMAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email-sender-password
            {{- end }}
            {{- end }}


{{- end }}
{{- end }}
