{{- if .Values.enabled }}
{{- if .Values.deploy_app }}
{{- if .Values.deployment.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "deployment_name" $ }}'
  namespace: {{ .Release.Namespace }}
  {{- if .Values.pixo_service_account.enabled }}
  annotations:
    platform.pixovr.com/service-account-name: '{{- include "pixo_sa_name" $ -}}'
  {{- end }}
  labels:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.microservice_name }}
    tier: backend
spec:
  replicas: {{ required "REQUIRED: replicas" .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: '{{ include "deployment_name" $ }}'
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- if .Values.linkerd.enabled }}
        linkerd.io/inject: enabled
        {{- end }}

        {{- if not .Values.debug.enabled }}
        container.apparmor.security.beta.kubernetes.io/{{- .Values.microservice_name -}}: runtime/default
        container.seccomp.security.alpha.kubernetes.io/{{- .Values.microservice_name -}}: runtime/default

        {{- if .Values.sql.proxy }}
        container.apparmor.security.beta.kubernetes.io/proxy: runtime/default
        container.seccomp.security.alpha.kubernetes.io/proxy: runtime/default
        {{- end }}

        {{- if .Values.clamav.enabled }}
        container.apparmor.security.beta.kubernetes.io/clamav: runtime/default
        container.seccomp.security.alpha.kubernetes.io/clamav: runtime/default
        {{- end }}

        {{- end }}

      labels:
        app: '{{ include "deployment_name" $ }}'
        namespace: {{ .Release.Namespace }}
        name: {{ .Values.microservice_name }}
        tier: backend
    spec:
      {{- if .Values.toleration }}
      tolerations:
      - key: {{ .Values.toleration }}
        operator: Equal
        value: "true"
        effect: PreferNoSchedule
      {{- end }}

      hostIPC: false
      hostNetwork: false
      hostPID: false
      {{- if not .Values.demo.enabled }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        supplementalGroups:
          - 150
      {{- end }}

      volumes:
        {{- if .Values.external_secrets.enabled }}
        {{- if .Values.external_secrets.app_secrets.enabled }}
        - name: app-secrets
          secret:
            secretName: app-secrets
        {{- end }}
        {{- end }}

        - name: tmp-dir
          emptyDir: {}
        - name: usr-tmp-dir
          emptyDir: {}
        - name: var-tmp-dir
          emptyDir: {}

        {{- if .Values.debug.enabled }}
        - name: config-dir
          emptyDir: {}
        {{- end }}

        {{- if .Values.cache.enabled }}
        - name: cache-dir
          emptyDir: {}
        {{- end }}

        {{- if eq .Values.microservice_name "api" }}
        - name: server-logs-dir
          emptyDir: {}
        {{- end }}

        {{- if .Values.node }}
        - name: npm-dir
          emptyDir: {}

        {{- else if .Values.nginx }}
        - name: body-dir
          emptyDir: {}
        - name: proxy-dir
          emptyDir: {}
        - name: cache-proxy-dir
          emptyDir: {}
        - name: cache-client-dir
          emptyDir: {}
        - name: fast-cgi-dir
          emptyDir: {}
        - name: uwsgi-dir
          emptyDir: {}
        - name: scgi-dir
          emptyDir: {}
        - name: pid-dir
          emptyDir: {}
        {{- end }}

        - name: db-volume
        {{- if and .Values.deployment.pvc.enabled .Values.deployment.pvc.mount }}
          persistentVolumeClaim:
            claimName: '{{- include "pvc_name" $ -}}'
        {{- else }}
          emptyDir: {}
        {{- end }}

        {{- if .Values.clamav.enabled }}
        - name: clamav-run
          emptyDir: {}
        - name: clamav-tmp
          emptyDir: {}

        - name: clamav-var-lib
        {{- if .Values.clamav.pvc.enabled }}
          persistentVolumeClaim:
            claimName: '{{- include "pvc_name" $ -}}-clamav'
        {{- else }}
          emptyDir: {}
        {{- end }}

        {{- end }}

      serviceAccountName: '{{ include "ksa_name" . }}'
      restartPolicy: Always
      containers:
      - name: {{ .Values.microservice_name }}
        image: '{{ include "image" . }}'
        imagePullPolicy: Always

        {{- if not .Values.demo.enabled }}
        securityContext:
          {{- if .Values.debug.enabled }}
          capabilities:
            add: 
            - SYS_PTRACE
          {{- else }}
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          {{- end }}
        {{- end }}

        resources:
          requests:
            memory: {{ required "REQUIRED: memory.request" .Values.memory.request }}
            cpu: {{ required "REQUIRED: cpu.request" .Values.cpu.request }}
          limits:
            memory: {{ required "REQUIRED: memory.limit" .Values.memory.limit }}
            cpu: {{ required "REQUIRED: cpu.limit" .Values.cpu.limit }}

        volumeMounts:
          {{- if .Values.external_secrets.enabled }}
          {{- if .Values.external_secrets.app_secrets.enabled }}
          - mountPath: /backend/secrets
            name: app-secrets
          {{- end }}
          {{- end }}
          - mountPath: {{ .Values.deployment.pvc.path }}
            name: db-volume
          - mountPath: /tmp
            name: tmp-dir
          - mountPath: /usr/tmp
            name: usr-tmp-dir
          - mountPath: /var/tmp
            name: var-tmp-dir

          {{- if .Values.debug.enabled }}
          - mountPath: /server/.config
            name: config-dir
          {{- end }}

          {{- if .Values.cache.enabled }}
          - mountPath: /.cache
            name: cache-dir
          {{- end }}

          {{- if eq .Values.microservice_name "api" }}
          - name: server-logs-dir
            mountPath: /apex-api/server/logs
          {{- end }}

          {{- if .Values.node }}
          - name: npm-dir
            mountPath: /.npm

          {{- else if .Values.nginx }}
          - name: body-dir
            mountPath: /var/lib/nginx/body
          - name: proxy-dir
            mountPath: /var/lib/nginx/proxy
          - name: cache-proxy-dir
            mountPath: /var/cache/nginx/proxy_temp
          - name: cache-client-dir
            mountPath: /var/cache/nginx/client_temp
          - name: fast-cgi-dir
            mountPath: /var/cache/nginx/fastcgi_temp
          - name: uwsgi-dir
            mountPath: /var/cache/nginx/uwsgi_temp
          - name: scgi-dir
            mountPath: /var/cache/nginx/scgi_temp
          - name: pid-dir
            mountPath: /var/run
          {{- end }}

        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
        {{- end }}

        {{- if .Values.cronjob.external_secrets.enabled }}
        envFrom:
        - secretRef:
            name: cronjob-secrets
        {{- end }}

        env:
        - name: USE_GCS
          value: "true"
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: DOMAIN
          value: '{{ include "full_domain" $ }}'
        - name: PORT
          value: "{{ .Values.containerPort }}"

        {{- if .Values.redis.enabled }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: '{{- .Release.Name -}}-{{- .Values.redis.secret_suffix -}}'
              key: redis-password
        {{- end }}

        {{- if .Values.crunchydb.enabled }}
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
              key: port
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
              key: dbname
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  '{{- include "db_name" $ -}}-pguser-{{- include "db_name" $ -}}'
              key: password
        {{- end }}

        {{- if .Values.google.pubsub.enabled }}
        - name: PUBSUB_TOPIC
          value: {{ include "pubsub_topic_name" $ }}
        - name: PUBSUB_SUBSCRIPTION
          value: {{ include "pubsub_subscription_name" $ }}
        - name: USE_PUBSUB
          value: "true"
        {{- end }}

        - name: TMP_PATH
          value: "/var/tmp"

        - name: GCP_PROJECT_ID
          value: "{{- include "app_project_id" $ -}}"

        - name: DB_PROJECT_ID
          value: "{{- include "db_project_id" $ -}}"

        - name: REGION
          value: "{{- .Values.google.region }}"

        {{- if .Values.sql.proxy }}
        - name: INSTANCE_NAME
          value: "{{- include "instance_name" $ -}}"
        {{- end }}

        {{- range .Values.dynamicHosts }}

        - name: {{ .key }}
        {{- if eq .type "local" }}
          value: {{ $.Release.Namespace -}}-{{- .service -}}.{{- $.Release.Namespace -}}.svc

        {{- else if eq .type "remote" }}

          {{- if .cluster }}

          {{- if .service }}
          value: {{ .protocol }}://{{- .cluster -}}.{{- .tenant -}}.{{- include "lifecycle_domain" $ -}}/{{- .service }}
          {{- else }}
          value: {{ .protocol }}://{{- .cluster -}}.{{- .tenant -}}.{{- include "lifecycle_domain" $ }}
          {{- end }}

          {{- else }}

          {{- if .service }}
          value: {{ .protocol }}://{{- .tenant -}}.{{- include "lifecycle_domain" $ }}/{{- .service }}
          {{- else }}
          value: {{ .protocol }}://{{- .tenant -}}.{{- include "lifecycle_domain" $ }}
          {{- end }}

          {{- end }}

        {{- end }}

        {{- end }}

        - name: LIFECYCLE
          value: {{ upper .Values.lifecycle }}

        - name: APP_ENV
          value: {{ upper .Values.lifecycle }}

        - name: NODE_ENV
          value: {{ upper .Values.lifecycle }}

        - name: APP_DOMAIN
          value: '{{- include "app_domain" $ -}}'

        - name: APP_URL
          value: https://{{- include "app_domain" $ }}

        {{- if .Values.sa_json_key.enabled }}
        - name: {{ .Values.sa_json_key.envKey }}
          value: /backend/secrets/svc-acct-json-key
        {{- end }}

        {{- if .Values.email.enabled }}
        - name: EMAILER_EMAIL
          value: {{ .Values.email.sender }}

        {{- if .Values.email.mfa }}
        - name: EMAILER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: email-sender-password
        {{- end }}

        {{- if .Values.email.bcc }}
        - name: EMAIL_BCC
          value: '{{- .Values.email.bcc -}}'
        {{- end }}

        {{- end }}

        {{- if .Values.google.storage.enabled }}

        {{- range .Values.google.storage.bucket_list }}
        - name: GOOGLE_STORAGE_{{ .key }}
          {{- if ne $.Values.cpl_cluster_name $.Values.cluster_name }}
          value: {{ $.Values.cluster_name -}}-{{- include "microservice_label" $ -}}-{{- .name }}
          {{- else }}
          value: {{ include "microservice_label" $ -}}-{{- .name }}
          {{- end }}
        {{- end }}

        {{- range .Values.google.storage.external_bucket_list }}
        - name: GOOGLE_STORAGE_{{ .key }}
          value: {{ include "app_label" $ -}}-{{- .external_service -}}-{{- .name }}
        {{- end }}

        {{- end }}


        {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 8 }}
        {{- end }}

        {{- if .Values.aws.auth.enabled }}
        - name: AWS_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-id

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-id

        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-secret

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-secret
        {{- end }}

        {{- if .Values.aws.cloudfront.enabled }}
        - name: AWS_CLOUDFRONT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-cf-public-key

        - name: AWS_CLOUDFRONT_PRIVATE_KEY_PATH
          value: /backend/secrets/aws-cf-private-key

        - name: AWS_CLOUDFRONT_DOMAIN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-cf-domain
        {{- end }}

        {{- if .Values.external_secrets.app_secrets.enabled }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: auth-key

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: auth-key
          {{- end }}

        {{- if .Values.external_auth }}
        - name: EXTERNAL_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: external-auth-key
        {{- end }}

        {{ if .Values.oauth.google.enabled }}
        - name: GOOGLE_OAUTH_ID
          valueFrom:
            secretKeyRef:
              name: oauth-credentials
              key: client_id

        - name: GOOGLE_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-credentials
              key: client_secret
        {{ end }}

        {{- if .Values.oauth.github.enabled }}
        - name: GITHUB_OAUTH_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: github-oauth-id

        - name: GITHUB_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: github-oauth-secret
        {{- end }}

        {{- if .Values.sql.proxy }}
        - name: DB_VENDOR
          value: "postgres"

        - name: {{ upper .Values.db.host_env_key }}
          value: "{{- .Values.db.host -}}"

        - name: {{ upper .Values.db.port_env_key }}
          value: "{{- .Values.db.port -}}"

        - name: {{ upper .Values.db.name_env_key }}
          value: '{{- include "db_name" . -}}'

        - name: {{ upper .Values.db.user_env_key }}
          value: '{{- include "app_sa" . -}}'

        - name: DB_DATABASE
          value: '{{- include "db_name" . -}}'

        {{- range .Values.google.sql.extra_databases }}

        - name: 'DB_DATABASE_{{- upper .name -}}'
          value: '{{- include "db_name" $ -}}-{{- .name -}}'

        - name: 'DB_NAME_{{- upper .name -}}'
          value: '{{- include "db_name" $ -}}-{{- .name -}}'
        {{- end }}

        {{- end }}

        ports:
        - containerPort: {{ .Values.containerPort }}
          name: api-port

        {{- range .Values.extraPorts }}
        - containerPort: {{ .containerPort }}
          name: {{ .name }}
        {{- end }}

        {{- if .Values.debug.enabled }}
        - containerPort: {{ .Values.debug.containerPort }}
          name: debug
          protocol: TCP
        {{- end }}

      {{- if .Values.sql.proxy }}
      - name: proxy
        image: "{{ .Values.db.proxy_version }}"
        imagePullPolicy: Always
        command:
        - /cloud_sql_proxy
        - -instances={{- include "db_project_id" . -}}:{{- required "REQUIRED: google.region" .Values.google.region -}}:{{- include "instance_name" . }}=tcp:127.0.0.1:5432
        - -enable_iam_login

        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      {{- end }}

      {{- if .Values.clamav.enabled }}
      - name: clamav
        image: clamav/clamav:stable
        ports:
        - containerPort: 3310

        volumeMounts:
        - name: clamav-run
          mountPath: /run
        - name: clamav-tmp
          mountPath: /tmp
        - name: clamav-var-lib
          mountPath: /var/lib/clamav

        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
          seccompProfile:
            type: RuntimeDefault

      {{- if .Values.clamav.init }}
      initContainers:
      - name: init-chown
        image: busybox:1.33
        command: ["sh", "-c", "chown -R 101:101 /var/lib/clamav"]
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: true
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: clamav-var-lib
      {{- end }}

      {{- end }}

{{- end }}
{{- end }}
{{- end }}

