{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.external_secrets.enabled }}
{{- if .Values.deploy_app }}

{{- if .Values.external_secrets.secret_store.enabled }}

apiVersion: external-secrets.io/v1beta1 
kind: SecretStore
metadata:
  name: {{ include "secret_store" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ include "app_project_id" $ }}

---
{{- end }}

{{- if .Values.cronjob.enabled }}

apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: cron-auth-secret
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "secret_store" $ }}
  target:
    name: cron-auth-secret
    creationPolicy: Owner
  data:
  - secretKey: EWN_USER
    remoteRef:
      key: ewn-username
  - secretKey: EWN_PASSWORD
    remoteRef:
      key: ewn-password

---
{{- end }}


{{- if or (.Values.google.iap.enabled) (.Values.google.iap.test.enabled) (.Values.oauth.google.enabled) }}

apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "secret_store" $ }}
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: google-oauth-id
  - secretKey: client_secret
    remoteRef:
      key: google-oauth-secret

---

{{- end }}

{{- if .Values.external_secrets.app_secrets.create }}

apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.external_secrets.refresh_interval }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  {{- end }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "secret_store" $ }}
  target:
    name: app-secrets
    creationPolicy: Owner
  data:

    - secretKey: auth-key
      remoteRef:
        key: {{ .Values.app_code -}}-auth-key

    {{- if or (.Values.google.sql.enabled) (.Values.sql.proxy) }}
    {{- if .Values.google.sql.use_password }}
    - secretKey: db-password
      remoteRef:
        key: db-password
    {{- end }}
    {{- end }}

    {{- if .Values.email.enabled }}
    {{- if .Values.email.mfa }}
    - secretKey: email-sender-password
      remoteRef:
        key: {{ .Values.app_code -}}-email-sender-password
    {{- end }}
    {{- end }}

    {{- if .Values.external_auth }}
    - secretKey: external-auth-key
      remoteRef:
        key: {{ .Values.app_code -}}-external-auth-key
    {{- end }}

    {{- if .Values.aws.auth.enabled }}
    - secretKey: aws-id
      remoteRef:
        key: {{ .Values.app_code -}}-aws-id

    - secretKey: aws-secret
      remoteRef:
        key: {{ .Values.app_code -}}-aws-secret
    {{- end }}

    {{- if .Values.aws.cloudfront.enabled }}
    - secretKey: aws-cf-private-key
      remoteRef:
        key: {{ .Values.app_code -}}-aws-cf-private-key

    - secretKey: aws-cf-public-key
      remoteRef:
        key: {{ .Values.app_code -}}-aws-cf-public-key

    - secretKey: aws-cf-domain
      remoteRef:
        key: {{ .Values.app_code -}}-aws-cf-domain
    {{- end }}

    {{- if .Values.oauth.github.enabled }}
    - secretKey: github-oauth-id
      remoteRef:
        key: github-oauth-id

    - secretKey: github-oauth-secret
      remoteRef:
        key: github-oauth-secret
    {{- end }}

    {{- if .Values.oauth.facebook.enabled }}
    - secretKey: facebook-oauth-id
      remoteRef:
        key: facebook-oauth-id

    - secretKey: facebook-oauth-secret
      remoteRef:
        key: facebook-oauth-secret
    {{- end }}

    {{- if .Values.oauth.twitter.enabled }}
    - secretKey: twitter-api-key
      remoteRef:
        key: twitter-api-key

    - secretKey: twitter-api-key-secret
      remoteRef:
        key: twitter-api-key-secret
    {{- end }}

    {{- if .Values.sa_json_key.enabled }}
    - secretKey: svc-acct-json-key
      remoteRef:
        key: {{ .Values.app_code -}}-svc-acct-json-key
    {{- end }}

    {{- if .Values.sendgrid.enabled }}
    - secretKey: sendgrid-key
      remoteRef:
        key: sendgrid-key
    {{- end }}

{{- end }}

{{- end }}
{{- end }}


{{- end }}
