{{- if .Values.google.wi_test }}

apiVersion: v1
kind: Pod
metadata:
  name: gcloud
spec:
  containers:
  - image: google/cloud-sdk
    name: gcloud
    command: ["gcloud"]
    args: ["auth", "list"]
  serviceAccountName: {{ include "ksa_name" . }}

{{- end }}
