{{- if .Values.enabled }}
{{- if .Values.deploy_app }}
{{- if .Values.deployment.enabled }}
{{- if .Values.hpa.enabled }}

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{- include "deployment_name" $ -}}-hpa'
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ include "deployment_name" $ }}'
  minReplicas: {{ .Values.hpa.min_replicas }}
  maxReplicas: {{ .Values.hpa.max_replicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.scale_down.stabilization_window_sec }}
      policies:
      - type: {{ .Values.hpa.scale_down.type }}
        value: {{ .Values.hpa.scale_down.value }}
        periodSeconds: {{ .Values.hpa.scale_down.period_seconds }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.scale_up.stabilization_window_sec }}
      policies:
      - type: {{ .Values.hpa.scale_up.type }}
        value: {{ .Values.hpa.scale_up.value }}
        periodSeconds: {{ .Values.hpa.scale_up.period_seconds }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: {{ .Values.hpa.target_mem }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.average_utilization }}

---

{{- end }}
{{- end }}
{{- end }}
{{- end }}
