{{- if .Values.enabled }}
{{- if .Values.create_infra }}
{{- if .Values.google.create_ip }}

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: {{ include "ip_name" $ }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project" $ }}
  labels:
    namespace: {{ .Release.Namespace }}
spec:
  location: global
  ipVersion: IPV4

{{- end }}
{{- end }}
{{- end }}
