{{- if .Values.create_infra }}
{{- if .Values.google.create_monitoring_suite }}

apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringAlertPolicy
metadata:
  name: {{ include "app_label" . -}}-alert-policy
  namespace: {{ $.Release.Namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" $ }}
spec:
  enabled: true
  displayName: {{ include "app_label" . }} Alert Policy
  notificationChannels:
    - external: "projects/{{- include "gke_project_id" $ -}}/notificationChannels/{{- required "REQUIRED: google.notification_channel" .Values.google.notification_channel -}}"
  combiner: OR
  conditions:
    - displayName: Uptime check running
      conditionAbsent:
        filter: metric.type="monitoring.googleapis.com/uptime_check/check_passed" AND metric.label.check_id="{{- include "app_label" $ }}" AND resource.type="uptime_url"
        duration: 3900s

---

apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringUptimeCheckConfig
metadata:
  name: uptime-check
  namespace: {{ $.Release.Namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" $ }}
spec:
  projectRef:
    external: projects/{{- include "gke_project_id" $ }}
  resourceID: {{ include "app_label" $ -}}-uptime-check
  displayName: {{ include "app_label" $ }}-uptime-check
  period: 600s
  timeout: 30s
  selectedRegions:
    - USA
  monitoredResource:
    type: uptime_url
    filterLabels:
      host: {{ include "domain" $ }}
      project_id: {{ include "gke_project_id" $ }}
  httpCheck:
    requestMethod: GET
    path: /health/
    port: 443
    useSsl: true
    validateSsl: true
    maskHeaders: true

{{- end }}
{{- end }}
