{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.mci }}
{{- if .Values.deploy_app }}
{{- if or (not .Values.multi_cluster) (eq .Values.cpl_cluster_name .Values.cluster_name) }}

apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: ingress-mci
  namespace: {{ $.Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    backstage.io/kubernetes-id: {{ .Values.app_code }}
  annotations:
    configsync.gke.io/cluster-name-selector: {{ include "primary_cluster" $ }}
    networking.gke.io/static-ip: {{ include "ip_name" $ }}
    networking.gke.io/managed-certificates: google-cert
    # networking.gke.io/frontend-config: gke-frontendconfig
    {{- if $.Values.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "domain" $ -}}.
    {{- end }}

spec:
  template:
    spec:
      backend:
        serviceName: nginx-mcs
        servicePort: 443

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

