{{- if .Values.create_infra }}
{{- if .Values.google.pubsub.enabled }}

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: {{ include "app_label" $ -}}-topic
  annotations: 
    cnrm.cloud.google.com/project-id: {{ include "app_label" $ }}
spec:
  schemaSettings:
    encoding: JSON

{{- end }}
{{- end }}
