{{- if .Values.create_infra }}
{{- if .Values.google.pubsub.enabled }}

{{- if .Values.google.pubsub.subscription.create }}
---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {{ include "pubsub_subscription_name" $ }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" $ }}
spec:
  ackDeadlineSeconds: {{ .Values.google.pubsub.subscription.ackDeadlineSeconds }}
  messageRetentionDuration: {{ .Values.google.pubsub.subscription.messageRetentionDuration }}
  retainAckedMessages: {{ .Values.google.pubsub.subscription.retainAckedMessages }}
  topicRef:
    name: {{ include "pubsub_topic_name" $ }}
  {{- if .Values.google.pubsub.subscription.push.enabled }}
  pushConfig:
    {{- if .Values.google.pubsub.subscription.push.custom_endpoint.enabled }}
    pushEndpoint: 'https://{{- include "custom_pubsub_push_domain" $ -}}/{{- .Values.google.pubsub.subscription.push.endpoint }}'
    {{- else }}
    pushEndpoint: 'https://{{- include "full_domain" $ -}}/{{- .Values.google.pubsub.subscription.push.endpoint }}'
    {{- end }}
  {{- end }}

{{- end }}

{{- range .Values.google.pubsub.topics }}
---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: {{ .name -}}-{{ include "pubsub_topic_name" $ }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" $ }}

{{- if .schema }}
spec:
  schemaSettings:
    schemaRef:
      name: {{ .schema.name -}}-{{ include "pubsub_topic_name" $ -}}-schema
    {{- if .schema.encoding }}
    encoding: {{ .schema.encoding }}
    {{- end }}
{{- end }}

{{- end }}


{{- range .Values.google.pubsub.schemas }}
---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: {{ .name -}}-{{ include "pubsub_topic_name" $ -}}-schema
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" $ }}
spec:
  type: '{{- .type -}}'
  projectRef:
    external: {{ include "app_project_id" $ }}

{{- end }}


{{- end }}
{{- end }}
