{{- if .Values.create_infra }}
{{- if .Values.google.pubsub.enabled }}

{{- range .Values.google.pubsub.topics }}
---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: {{ .name -}}-{{ include "pubsub_topic_name" $ }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" $ }}

{{- if .schema }}
spec:
  schemaSettings:
    schemaRef:
      name: {{ .schema.name -}}-{{ include "pubsub_topic_name" $ -}}-schema
    {{- if .schema.encoding }}
    encoding: {{ .schema.encoding }}
    {{- end }}
{{- end }}

{{ $topic := . }}
{{- range .subscriptions }}
---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {{ $topic.name -}}-{{ include "pubsub_subscription_name" $ }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" $ }}
spec:
  ackDeadlineSeconds: {{ $.Values.google.pubsub.subscription.ackDeadlineSeconds }}
  messageRetentionDuration: {{ $.Values.google.pubsub.subscription.messageRetentionDuration }}
  retainAckedMessages: {{ $.Values.google.pubsub.subscription.retainAckedMessages }}
  topicRef:
    name: {{ $topic.name -}}-{{ include "pubsub_topic_name" $ }}
  {{- if .push }}
  pushConfig:
    {{- if .push.region }} 
    pushEndpoint: 'https://{{- .push.region -}}.{{- .push.service -}}.{{- .push.tenant -}}.{{- include "lifecycle_domain" $ -}}/{{- .push.endpoint }}'
    {{- else }}
    pushEndpoint: 'https://{{- .push.service -}}.{{- .push.tenant -}}.{{- include "lifecycle_domain" $ -}}/{{- .push.endpoint }}'
    {{- end }}
  {{- end }}

{{- end }}


{{- end }}


{{- range .Values.google.pubsub.schemas }}
---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: {{ .name -}}-{{ include "pubsub_topic_name" $ -}}-schema
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" $ }}
spec:
  type: '{{- .type -}}'
  projectRef:
    external: {{ include "app_project_id" $ }}

{{- end }}


{{- end }}
{{- end }}
