{{- if and (.Values.enabled) (.Values.use_pd) }}
{{- if .Values.deploy_app }}
{{- if .Values.deployment.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "REQUIRED: disk_size" .Values.disk_size }}

{{- end }}
{{- end }}
{{- end }}
