{{- if and (.Values.enabled) (.Values.deployment.pvc.enabled) }}
{{- if .Values.deploy_app }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{- include "pvc_name" $ -}}'
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.deployment.pvc.storage_class_name }}
  accessModes:
    - {{ required "REQUIRED: deployment.pvc.access_mode" .Values.deployment.pvc.access_mode }}
  resources:
    requests:
      storage: {{ required "REQUIRED: deployment.pvc.disk_size" .Values.deployment.pvc.disk_size }}

{{- end }}
{{- end }}
