{{- if and (.Values.enabled) (.Values.deployment.pvc.enabled) }}
{{- if .Values.deploy_app }}
{{- if .Values.deployment.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{- include "pvc_name" $ -}}'
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    backstage.io/kubernetes-id: {{ .Values.app_code }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "REQUIRED: deployment.pvc.disk_size" .Values.deployment.pvc.disk_size }}

{{- end }}
{{- end }}
{{- end }}
