{{- if .Values.deploy_app }}

{{- if not .Values.external_secrets.enabled }}
{{- if .Values.secrets.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  FAKE_DATA: YWRtaW4=
  DB_PASSWORD: {{ .Values.db.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
type: Opaque
data:
  client_id: YWRtaW4=
  client_secret: YWRtaW4=

{{- end }}
{{- end }}
{{- end }}
