{{- if .Values.enabled }}
{{- if .Values.create_sa }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ksa_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
  {{- if not .Values.local }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "app_sa" . }}.gserviceaccount.com
  {{- end }}

{{- end }}
{{- end }}
