{{- if .Values.enabled }}
{{- if .Values.deploy_app }}
{{- if .Values.deployment.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "service_name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    tier: backend
    backstage.io/kubernetes-id: {{ .Values.app_code }}
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{- .Release.Name -}}-backendconfig"}'
    {{- if .Values.ingress.nginx }}
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.service.internal }}
    networking.gke.io/load-balancer-type: "Internal"
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- if .Values.service.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: '{{ include "full_domain" $ -}}.'
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.nginx }}
  type: LoadBalancer
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  selector:
    app: {{ include "deployment_name" $ }}

  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: {{ .Values.containerPort }}

  {{- range .Values.extraPorts }}

  {{- if .exposeInService }}
  - name: {{ .name }}
    port: {{ .hostPort }}
    protocol: TCP
    targetPort: {{ .containerPort }}
  {{- end }}

  {{- end }}

{{- end }}
{{- end }}
{{- end }}
