{{- if .Values.enabled }}
{{- if .Values.deploy_app }}
{{- if .Values.deployment.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "service_name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    tier: backend
    backstage.io/kubernetes-id: {{ .Values.app_code }}
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{- .Release.Name -}}-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
    {{- if .Values.ingress.nginx }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "deployment_name" $ }}
    
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: {{ .Values.containerPort }}

  {{- range .Values.extraPorts }}

  {{- if .exposeInService }}
  - name: {{ .name }}
    port: {{ .containerPort }}
    protocol: TCP
    targetPort: {{ .containerPort }}
  {{- end }}

  {{- end }}

{{- end }}
{{- end }}
{{- end }}
