{{- if and (.Values.enabled) (not .Values.local) }}
{{- if .Values.deploy_app }}
{{- if .Values.sftpgo.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sftpgo-admin
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ include "secret_store" $ }}
  target:
    name: sftpgo-admin
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: {{ include "sftpgo.cluster_prefix" $ -}}sftpgo-admin-password

{{- if include "sftpgo.host_keys_enabled" $ }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sftpgo-host-keys
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ include "secret_store" $ }}
  target:
    name: sftpgo-host-keys
    creationPolicy: Owner
  data:
  {{- range splitList " " (include "sftpgo.host_key_types" $) }}
  - secretKey: ssh_host_{{ . }}_key
    remoteRef:
      key: {{ include "sftpgo.cluster_prefix" $ -}}sftpgo-host-key-{{ . }}
  {{- end }}
{{- end }}

{{- $passwords := list }}
{{- range (include "sftpgo.accounts" $ | fromJson).accounts }}
  {{- if .password }}{{- $passwords = append $passwords .username }}{{- end }}
{{- end }}
{{- if $passwords }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sftpgo-account-passwords
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ include "secret_store" $ }}
  target:
    name: sftpgo-account-passwords
    creationPolicy: Owner
  data:
  {{- range $passwords }}
  - secretKey: {{ . | quote }}
    remoteRef:
      key: {{ include "sftpgo.cluster_prefix" $ -}}sftpgo-user-{{ . }}-password
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
