{{- if .Values.create_infra }}
{{- if .Values.google.storage.enabled }}
{{- if .Values.google.storage.create }}

{{- range .Values.google.storage.bucket_list }}

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ include "microservice_label" $ -}}-{{- .name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" $ }}
    cnrm.cloud.google.com/force-destroy: "false"
  labels:
    namespace: {{ $.Release.Namespace }}
spec:
  location: {{ required "REQUIRED: google.region" $.Values.google.region }}

  {{- if .retentionPolicy }}
  retentionPolicy:
    isLocked: {{ .retentionPolicy.isLocked }}
    retentionPeriod: {{ .retentionPolicy.retentionPeriod }}
  {{- else if $.Values.google.storage.retentionPolicy }}
  retentionPolicy:
    isLocked: {{ $.Values.google.storage.retentionPolicy.isLocked }}
    retentionPeriod: {{ $.Values.google.storage.retentionPolicy.retentionPeriod }}
  {{- end }}

  cors:

    {{- if $.Values.google.storage.cors.allow_all }}
    - origin: ["*"]
      method: ["*"]
    {{- else }}
    - origin: ["https://{{- include "app_domain" $ }}"]
      method: ["PUT", "POST", "GET", "HEAD"]
    {{- end }}
      responseHeader: {{ $.Values.google.storage.cors.headers }}
      maxAgeSeconds: 3600

    {{- if eq $.Values.lifecycle "dev" }}
    - origin: ["http://localhost"]
      method:
        - "PUT"
        - "POST"
        - "GET"
        - "HEAD"
      responseHeader: {{ $.Values.google.storage.cors.headers }}
      maxAgeSeconds: 3600
    {{- end }}
  uniformBucketLevelAccess: false

---

{{- if .viewing_tenant }}

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: {{ include "microservice_label" $ -}}-{{- .name -}}-bucket-access
spec:
  bucketRef:
    name: {{ include "microservice_label" $ -}}-{{- .name }}
  entity: user-{{ .viewing_tenant -}}-{{- .viewing_service -}}@{{- .viewing_tenant -}}-{{- $.Values.lifecycle -}}-sa-project.iam.gserviceaccount.com
  {{- if .viewing_role }}
  role: {{ .viewing_role }}
  {{- else }}
  role: READER
  {{- end }}

---

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageDefaultObjectAccessControl
metadata:
  name: {{ include "microservice_label" $ -}}-{{- .name -}}-access
spec:
  bucketRef:
    name: {{ include "microservice_label" $ -}}-{{- .name }}
  entity: user-{{ .viewing_tenant -}}-{{- .viewing_service -}}@{{- .viewing_tenant -}}-{{- $.Values.lifecycle -}}-sa-project.iam.gserviceaccount.com
  {{- if .viewing_role }}
  role: {{ .viewing_role }}
  {{- else }}
  role: READER
  {{- end }}

---
{{- end }}

{{- end }}

{{- end }}
{{- end }}
{{- end }}
