{{- if .Values.create_infra }}
{{- if .Values.google.storage.enabled }}
{{- if .Values.google.storage.create }}

{{- range .Values.google.storage.bucket_list }}

apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ include "app_label" $ -}}-{{- .name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project" $ }}
    cnrm.cloud.google.com/force-destroy: "false"
  labels:
    namespace: {{ $.Release.Namespace }}
spec:
  location: {{ required "REQUIRED: google.region" $.Values.google.region }}
  # cors:
  #   - origin: ["https://{{- include "subdomain" $ -}}"]
  #     responseHeader: ["Content-Type"]
  #     method: ["*"]
  #     maxAgeSeconds: 3600
  uniformBucketLevelAccess: true

---

{{- end }}

{{- end }}
{{- end }}
{{- end }}
