---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ include "fullname" $ }}
  namespace: {{ .Values.argocd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    tier: platform
    deployment: helm
spec:
  generators:
  - matrix:
      generators:
        - git:
            repoURL: git@github.com:{{- .Values.github_org }}/{{- .Values.repo_name -}}.git
            revision: {{ .Values.revision }}
            files:
            - path: {{ .Values.file_path }}
        {{- if .Values.multi_cluster }}
        - clusters: {}
        {{- end }}
  template:
    metadata:
      {{- if .Values.multi_cluster }}
      name: '{{ "{{ nameNormalized }}" }}-{{ "{{ path.basename }}" }}-apps'
      {{- else }}
      name: '{{ "{{ path.basename }}" }}-apps'
      {{- end }}
      annotations:
        argocd.argoproj.io/sync-wave: "20"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        tier: tenant
        deployment: helm
    spec:
      project: {{ .Values.argocd_project_name }}
      source:
        repoURL: {{ .Values.apps.chart.repoURL }}
        chart: {{ .Values.apps.chart.name }}
        targetRevision: {{ .Values.apps.chart.version }}
        helm:
          values: |
            cpl_cluster_name: {{ .Values.cpl_cluster_name }}
            cluster_name: {{ "{{ server }}" }}
            fullname: {{ "{{ path.basename }}" }}
            github_org: {{ required "github_org" .Values.github_org }} 
            repo_name: {{ required "repo_name" .Values.repo_name }}
            app_domain: '{{ "{{ app.domain }}" }}'
            app_name: '{{ "{{ path.basename }}" }}'
            app_project_id: '{{ "{{ app.app_project_id }}" }}'
            sa_project_id: '{{ "{{ app.sa_project_id }}" }}'
            infra: 
              namespace: {{ .Values.infra_namespace }}
            iam:
              namespace: {{ .Values.iam_namespace }}
      destination:
        server: {{ .Values.destination_server }}
        namespace: {{ .Values.argocd_namespace }}


