---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-operator-controller-manager
  namespace: '{{- .Release.Namespace -}}'
  labels:
    app.kubernetes.io/version: '{{- .Chart.AppVersion -}}'
    app.kubernetes.io/component: controller-manager
    control-plane: controller-manager
    {{- range $key, $value := .Values.defaultLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
          imagePullPolicy: '{{- .Values.manager.image.pullPolicy -}}'
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          command:
            - /manager
          env:
            - name: NAMESPACE
              value: '{{- .Release.Namespace -}}'
            - name: REGION
              value: '{{- include "region" $ -}}'
            - name: LIFECYCLE
              value: '{{- include "lifecycle" $ -}}'
            - name: PIXO_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pixo-platform-credentials
            - name: PIXO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pixo-platform-credentials
          image: '{{ .Values.manager.image.repository }}:{{- include "manager.imageTag" $ -}}'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: platform-operator-controller-manager
      terminationGracePeriodSeconds: 10
