{{- if .Values.gcpsm.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-operator-pixo-platform-credentials
  labels:
    app.kubernetes.io/version: '{{- .Chart.AppVersion -}}'
    app.kubernetes.io/component: secrets
    {{- range $key, $value := .Values.defaultLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  data:
    - remoteRef:
        key: '{{- .Values.gcpsm.apiKey.remoteKey -}}'
      secretKey: api-key
  refreshInterval: '{{- .Values.gcpsm.refreshInterval -}}'
  secretStoreRef:
    kind: SecretStore
    name: platform-operator-pixo-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pixo-platform-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: platform-operator-pixo-secret-store
  namespace: '{{- .Release.Namespace -}}'
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secrets
    {{- range $key, $value := .Values.defaultLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  provider:
    gcpsm:
      projectID: '{{- required "REQUIRED: gcpsm.projectId" .Values.gcpsm.projectId -}}'

  {{- end }}
