---
apiVersion: v1
kind: Service
metadata:
  name: platform-operator-controller-manager-metrics-service
  namespace: '{{- .Release.Namespace -}}'
  labels:
    app.kubernetes.io/version: '{{- .Chart.AppVersion -}}'
    app.kubernetes.io/component: metrics
    {{- range $key, $value := .Values.defaultLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
