apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrict-role-bindings
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["RoleBinding"]
  parameters:
      restrictedRole:
        name: "admin"
