{{- if .Values.config_connector.enabled }}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: '{{ include "infra_sa_name" $ }}'
  namespace: {{ .Values.target_namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "sa_project_id" $ }}
spec:
  displayName: "{{ .Release.Name }} infra admin service account"

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: '{{ include "infra_sa_name" $ -}}-wi'
  namespace: {{ .Values.target_namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "sa_project_id" $ }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: '{{ include "infra_sa_name" $ }}'
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
      - serviceAccount:{{- include "gke_project_id" $ -}}.svc.id.goog[cnrm-system/cnrm-controller-manager-{{- required "REQUIRED: app.namespace" .Values.app.namespace -}}]


{{- end }}
