
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ .Release.Name -}}-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ include "app_project_id" $ }}
  bindings:
    {{- range .Values.app.roles }}
    - role: roles/{{- . }}
      members:
      - memberFrom:
          serviceAccountRef:
            name: '{{ include "sa_name" $ }}'
            namespace: {{ $.Release.Namespace }}
    {{- end }}

