{{- if .Values.enabled }}
{{- if .Values.add_bindings }}
{{- if .Values.sa.enabled }}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ .Release.Name -}}-sa-policy
  namespace: {{ .Values.target_namespace }}
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: '{{ include "sa_project_id" $ }}'
  bindings:
    {{- range .Values.sa.infra_roles }}
    - role: roles/{{- . }}
      members:
      - memberFrom:
          serviceAccountRef:
            name: '{{ include "infra_sa_name" $ }}'
            namespace: {{ $.Release.Namespace }}
    {{- end }}
    {{- range .Values.sa.app_roles }}
    - role: roles/{{- . }}
      members:
      - memberFrom:
          serviceAccountRef:
            name: '{{ include "sa_name" $ }}'
            namespace: {{ $.Release.Namespace }}
    {{- end }}

{{- end }}
{{- end }}
{{- end }}
