
github_org: PixoVR
repo_name: replace-me
github_team: platforms

revision: HEAD
target_revision: HEAD

project_name: platform
argocd_cpl_project: cluster-addons
destination_server: https://kubernetes.default.svc
sync_wave: '-100'

cpl_cluster_addon_charts_filepath: kustomize/addons/charts/*/cpl-config.yaml
cpl_cluster_addon_manifests_filepath: kustomize/addons/manifests/*/cpl-config.yaml

app_cluster_addon_charts_filepath: kustomize/addons/charts/*/app-config.yaml
app_cluster_addon_manifests_filepath: kustomize/addons/manifests/*/app-config.yaml

gcp_dns_project_id: replace-me-123
